### ISSUE TITLE
[BUG] can't start with cluster 

### ISSUE THREAD

**Issue by yop0382** [streamnative/aop#324]
**Describe the bug**
trying to start amqp with cluster charts from apache repo

and have 
```
java.lang.NoSuchMethodError: org.apache.pulsar.broker.ServiceConfigurationUtils.getAppliedAdvertisedAddress(Lorg/apache/pulsar/broker/ServiceConfiguration;)Ljava/lang/String;
	at io.streamnative.pulsar.handlers.amqp.AmqpProtocolHandler.start(AmqpProtocolHandler.java:98) ~[?:?]
	at org.apache.pulsar.broker.protocol.ProtocolHandlerWithClassLoader.start(ProtocolHandlerWithClassLoader.java:66) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
	at org.apache.pulsar.broker.protocol.ProtocolHandlers.lambda$start$4(ProtocolHandlers.java:141) ~[org.apache.pulsar-pulsar-broker-2.7.2.jar:2.7.2]
```
used this configurations : 

```
FROM apachepulsar/pulsar-all:2.7.2
RUN curl -vL https://github.com/streamnative/pulsar-io-amqp-1-0/releases/download/v2.8.1.21/pulsar-io-amqp1_0-2.8.1.21.nar -o /pulsar/connectors/pulsar-io-amqp1_0-2.8.1.21.nar
RUN mkdir /pulsar/protocols && curl -vL https://github.com/streamnative/aop/releases/download/v2.7.2.9/pulsar-protocol-handler-amqp-2.7.2.9.nar -o /pulsar/protocols/pulsar-protocol-handler-amqp-2.7.2.9.nar
RUN echo 'amqpListeners=amqp://127.0.0.1:5672' >> /pulsar/conf/broker.conf
RUN echo 'protocolHandlerDirectory=./protocols' >> /pulsar/conf/broker.conf
RUN echo 'messagingProtocols=amqp' >> /pulsar/conf/broker.conf
RUN echo 'brokerServicePort=6650' >> /pulsar/conf/broker.conf
RUN echo 'amqpProxyEnable=true' >> /pulsar/conf/broker.conf
RUN echo 'amqpProxyPort=5682' >> /pulsar/conf/broker.conf
```

any idea ?

**Comment by yop0382** [comment]
trying with this patch https://github.com/streamnative/aop/commit/1df962d830f20df5393caeb7026083ec74db2502

**Comment by yop0382** [comment]
with 2.8.0 
 https://github.com/apache/pulsar/blob/v2.8.0/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfigurationUtils.java
https://github.com/streamnative/aop/commit/1df962d830f20df5393caeb7026083ec74db2502 can't work
but with 2.8.1
https://github.com/apache/pulsar/blob/v2.8.1/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfigurationUtils.java
normaly it will work ...

**Comment by yop0382** [comment]
Working with 2.8.1 & 2.8.0.16

FROM apachepulsar/pulsar-all:2.8.1
RUN curl -vL https://github.com/streamnative/pulsar-io-amqp-1-0/releases/download/v2.8.1.21/pulsar-io-amqp1_0-2.8.1.21.nar -o /pulsar/connectors/pulsar-io-amqp1_0-2.8.1.21.nar
RUN mkdir /pulsar/protocols && curl -vL https://github.com/streamnative/aop/releases/download/v2.8.0.16/pulsar-protocol-handler-amqp-2.8.0.16.nar -o /pulsar/protocols/pulsar-protocol-handler-amqp-2.8.0.16.nar
RUN echo 'amqpListeners=amqp://127.0.0.1:5672' >> /pulsar/conf/broker.conf
RUN echo 'protocolHandlerDirectory=./protocols' >> /pulsar/conf/broker.conf
RUN echo 'messagingProtocols=amqp' >> /pulsar/conf/broker.conf
RUN echo 'brokerServicePort=6650' >> /pulsar/conf/broker.conf
RUN echo 'amqpProxyEnable=true' >> /pulsar/conf/broker.conf
RUN echo 'amqpProxyPort=5682' >> /pulsar/conf/broker.conf

**Comment by gaoran10** [comment]
Please use the same version for Pulsar and AoP.
