### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tspannhw** [streamnative/aop#722]
**Describe the bug**
Send fails on Pulsar 2.10.1 server as AOP/RabbitMQ libraries don't set a producer.

**To Reproduce**

send a message

https://github.com/tspannhw/airquality/blob/main/src/main/java/dev/datainmotion/airquality/service/AMQPService.java

**Expected behavior**

messages sends to topic no error

**Screenshots**

amqp send 	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "producerName" is null
	at org.apache.pulsar.broker.service.persistent.MessageDeduplication.isDuplicate(MessageDeduplication.java:327) ~[org.apache.pulsar-pulsar-broker-2.10.1.jar:2.10.1]
	at org.apache.pulsar.broker.service.persistent.PersistentTopic.publishMessage(PersistentTopic.java:428) ~[org.apache.pulsar-pulsar-broker-2.10.1.jar:2.10.1]
	at io.streamnative.pulsar.handlers.amqp.MessagePublishContext.publishMessages(MessagePublishContext.java:103) ~[?:?]
	at io.streamnative.pulsar.handlers.amqp.impl.PersistentExchange.writeMessageAsync(PersistentExchange.java:112) ~[?:?]
	at io.streamnative.pulsar.handlers.amqp.AmqpChannel.lambda$deliverCurrentMessageIfComplete$8(AmqpChannel.java:552) ~[?:?]

**Comment by mingyifei** [comment]
[#530](https://github.com/streamnative/aop/pull/530)

**Comment by mingyifei** [comment]
You can try version 2.11.
